---

fsstretch_key_url: "https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc"

freeswitch_repo_gpg: "https://freeswitch.signalwire.com/repo/deb/debian-release/signalwire-freeswitch-repo.gpg"

freeswitch_repo: "https://freeswitch.signalwire.com/repo/deb/debian-release/"

freeswitch_unstable_repo: "https://freeswitch.signalwire.com/repo/deb/debian-unstable/"

freeswitch_gpg_key: "[signed-by=/usr/share/keyrings/signalwire-freeswitch-repo.gpg]"

freeswitch_signalwire_user: "signalwire"

freeswitch_signalwire_token: "pat_nQFdYaeLMCNLuZZMk3XfpwYd"

vault_freeswitch_signalwire_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62623931363561376363666130396662623831363462353132633632663863356162393635646263
          3861393264663366346366393035656363646236313864350a633064373662346137343039626332
          61313865386261303138626133396538306134663539366232343661646332383564633437633063
          3731363937373839320a626565663465333838386231383034383462613639323533313162376663

vault_freeswitch_signalwire_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65646139346464333166306530626664356534663436643037303435666561643031633539356131
          3031646361643063306532393661666338373764363033360a373736356464653933613032356365
          62313633323338653634636238333438623834643239333163313337396166633362646130363162
          3162623364323863300a653137303165333138636533306338663534363839323437643766306137
          34356438386531636334336263636435623832366566313161343061323761626462